### ISSUE TITLE
Do you have the training and validation data?

### ISSUE THREAD

**Issue by ynuwm** [saitiku/rbf#1]
Hi, I'm interested in this repository, in this code:
```
training_df = pd.read_csv("data/bcinfill-s6-run1.csv")
validation_df = pd.read_csv("data/bcinfill-s6-run2.csv")
```
can you share the training and validation data to me? Thank you.

**Comment by saideeptiku** [comment]
Hi,

Sorry, I do not own the data that I used. You can most certainly use fingerprinting data available for open access.
